import { plainToClass } from 'class-transformer'
import faker from 'faker'
import jwt, { JsonWebTokenError } from 'jsonwebtoken'
import { Unauthorized, NotFound } from 'http-errors'
//import { LoginDto } from '../dtos/auths/request/login.dto'
//import { clearDatabase, prisma } from '../prisma'
//import { UserFactory } from '../utils/factories/user.factory'
//import { TokenFactory } from '../utils/factories/token.factory'
import { AuthService } from './auth.service'
